### ISSUE TITLE
Question from Sifan Liu, Ziheng Ru, and Runxing Wang 

### ISSUE THREAD

**Issue by CarolLiuSifan** [beanumber/sds192-mp2#11]
When we were wrangling the house elections and contributions datasets, we noticed there are a lot of contributions made by third party committees or even unknown party committees. I think that we should focus on Democrats and Republicans as these are the largest parties during the house election.  Though I am also not sure if that would infect our data's accuracy.

**Comment by RubyRu** [comment]
I think it's okay to only include Democrats and Republicans as we are only comparing which of these two parties made more contributions. But we need to clearly state the effect of third-party committees. It's also very interesting yet frustrating when we found out that party committees didn't play a role as important as we have imagined. I'm interested in learning more about the individuals that made large contributions to the election and the effect of parties on the presidential election.

**Comment by RebeccaRunxinWang** [comment]
Actually, more committees are not affiliated to any party than to third party. I think it's impossible to include third party: too complicated for data wrangling. Also the influence of third party is limited. We should filter() committee_affiliation to just R and D, thus the problem would be clearer to be solved.
