### ISSUE TITLE
Combining tables

### ISSUE THREAD

**Issue by nacklin** [beanumber/sds192-mp2#15]
Our project so far is to find a relationship between contributions of candidates and general election wins. Variables to focus on are: Cand_name, contribution # (number of rows the candidate appeared in), sum of contributions, party, win (0 or 1). 

We want to combine the house elections ge_winner variable to the contribution1 table.

**Comment by beanumber** [comment]
Please post this to (https://github.com/christine-chu/sds192-mp2)
