### ISSUE TITLE
Assign Task

### ISSUE THREAD

**Issue by zixian97** [beanumber/sds192-mp2#2]
Cindy is responsible for writing code for the 2 graphs
Zixian is in charged of revising the code, adding comments and writing codes for the count
Lily works on writing the blog post and functions
We will all check each other's code

**Comment by beanumber** [comment]
Sounds like a plan! But these should be issues in (https://github.com/zixian97/sds192-mp2/), not in (https://github.com/beanumber/sds192-mp2/)
