### ISSUE TITLE
Problem joining tables--inconsistent name

### ISSUE THREAD

**Issue by crystalzang** [beanumber/sds192-mp2#4]
The cand name, committe name in the tables I wanna join are not consistent, such as the capitalization. How could we join tables?

**Comment by yiwangsds** [comment]
try join by their cand_id and cmtd_id? even though the names in 2 two sets are inconsistent, try to rename

**Comment by crystalzang** [comment]
Sounds good!

**Comment by beanumber** [comment]
@czang97 @yiwangsds Please put these issues in *your* repository!
